rescue_mission/config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "questions#index"
  resources :questions do
    resources :answers, only: [:destroy, :new, :create]
  end
end

rescue_mission/app/models/answer.rb
class Answer < ApplicationRecord
  validates :answer, presence: true, length: { minimum: 50 }

  belongs_to :question
end

rescue_mission/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rescue_mission/app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: { minimum: 20 }
  validates :description, presence: true, length: { minimum: 50 }

  has_many :answers
end

rescue_mission/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)

    @answer.question = @question

    if @answer.save
      flash[:alert] = "Answer was saved"
      redirect_to question_path(@question)
    else
      flash[:alert] = "Must provide a description that is at least 50 characters long"
      render :new
    end
  end

  private
   def answer_params
     params.require(:answer).permit(:answer)
   end
end

rescue_mission/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rescue_mission/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answers

  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    @question.destroy

    redirect_to questions_path
  end

  private
   def question_params
     params.require(:question).permit(:title, :description)
   end
end

rescue_mission/app/helpers/application_helper.rb
module ApplicationHelper
end

rescue_mission/app/helpers/questions_helper.rb
module QuestionsHelper
end

rescue_mission/app/views/answers/_form.html.erb
<%= form_for([@question, @answer]) do |f| %>

  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :answer %>
  <%= f.text_field :answer %>

  <%= f.submit "Submit" %>
<% end %>

rescue_mission/app/views/answers/new.html.erb
<h1>Submit Answer</h1>

<p><%= @question.description %></p>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

rescue_mission/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rescue_mission/app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit "Submit" %>
<% end %>

rescue_mission/app/views/questions/edit.html.erb
<h1>Edit Answer</h1>

<%= render 'form', question: @question %>

<%= link_to 'Delete Question', @question, method: :delete, data: {confirm: 'Are you sure?' }  %>

rescue_mission/app/views/questions/index.html.erb
<h1>Questions</h1>

<ul>
  <% @questions.each do |question| %>
    <li><%=  link_to question.title, question %></li>
  <% end %>
</ul>

<%= link_to 'Post Question', new_question_path %>

rescue_mission/app/views/questions/new.html.erb
<h1>Submit Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

rescue_mission/app/views/questions/show.html.erb
<p> Question: <br><%= @question.title %></p>
<p> Description: <br><%= @question.description %> </p>

<p>Answers:</p>

<ul>
  <% @answer.each do |answer| %>
    <li><%= answer.answer%></li>
  <% end %>
</ul>

<%= link_to 'Delete Question', @question, method: :delete, data: {confirm: 'Are you sure?' }  %>
<%= link_to 'Edit Question', edit_question_path(@question) %>
<%= link_to 'Post Answer', new_question_answer_path(@question) %>
<%= link_to 'Back', questions_path %>